### ISSUE TITLE
Designer-Modus Fehler bei JS-Dateien

### ISSUE THREAD

**Issue by rolandschuetz** [netzmacht/contao-theme-plus#88]
Hallo,

ich füge eine JavaScript-Datei auf folgende Weise hinzu.

```
$GLOBALS['TL_JAVASCRIPT'][] = new \Assetic\Asset\FileAsset(TL_ROOT . '/assets/jquery/core/1.11.0/jquery.min.js');
```

Im Produktiv-Modus funktioniert alles, aber im Designer-Modus erhalte ich folgenden Fehler:

```
Warning: filemtime(): stat failed for jquery.min.js in system/modules/theme-plus/classes/src/Bit3/Contao/ThemePlus/ThemePlus.php on line 1364

#0 [internal function]: __error(2, 'filemtime() [<a...', '/Users/roland/D...', 1364, Array)
#1 system/modules/theme-plus/classes/src/Bit3/Contao/ThemePlus/ThemePlus.php(1364): filemtime('jquery.min.js')
#2 system/modules/theme-plus/classes/src/Bit3/Contao/ThemePlus/ThemePlus.php(1140): Bit3\Contao\ThemePlus\ThemePlus->addAssetsToCollectionFromArray(Array, 'js', false, Object(Assetic\Asset\AssetCollection), Array, Object(Assetic\Filter\FilterCollection), 'body')
#3 system/modules/theme-plus/classes/src/Bit3/Contao/ThemePlus/ThemePlus.php(694): Bit3\Contao\ThemePlus\ThemePlus->parseJavaScripts(Object(Contao\LayoutModel), Array)
#4 system/modules/core/library/Contao/Controller.php(1778): Bit3\Contao\ThemePlus\ThemePlus->hookReplaceDynamicScriptTags('<!DOCTYPE html>...')
#5 system/modules/core/classes/FrontendTemplate.php(99): Contao\Controller::replaceDynamicScriptTags('<!DOCTYPE html>...')
#6 system/modules/core/pages/PageRegular.php(189): Contao\FrontendTemplate->output(true)
#7 index.php(260): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#8 index.php(444): Index->run()
#9 {main}
```

Diese Problem existiert seit dem Update auf 4.4.2. Habe ich hier einen Fehler drinnen, oder liegt das an Theme+?

**Comment by dmolineus** [comment]
Du schreibst, dass das Problem nach dem Update auf 4.4.2 auftrat. Welche Version hast du vorher genutzt?

**Comment by rolandschuetz** [comment]
Ist schon zu lange her um mich noch daran erinnern zu können. Sorry.

**Comment by dmolineus** [comment]
Behoben mit 37a925ef370335d0e983dd8f709b8ed249deb2b0. Nächstes Bugfix-Release beinhaltet dann den Fix.
