### ISSUE TITLE
check deprecated notice

### ISSUE THREAD

**Issue by frontendschlampe** [netzmacht/contao-theme-plus#96]
```
Deprecated notice: Deprecated, use Bit3\Contao\ThemePlus\Model\JavaScriptModel instead in composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/JavaScriptModel.php on line 14
#0 [internal function]: __error(16384, 'Deprecated, use...', '/home/XXX/...', 14, Array)
#1 composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/JavaScriptModel.php(14): trigger_error('Deprecated, use...', 16384)
#2 composer/vendor/composer/ClassLoader.php(412): include('/home/XXX/...')
#3 composer/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/home/XXX/...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('ThemePlus\Model...')
#5 composer/vendor/netzmacht/contao-theme-plus/src/Bit3/Contao/ThemePlus/DataContainer/Page.php(36): spl_autoload_call('ThemePlus\Model...')
#6 system/modules/core/library/Contao/Widget.php(1345): Bit3\Contao\ThemePlus\DataContainer\Page->getJavaScripts(Object(Contao\DC_Table))
#7 system/modules/core/classes/DataContainer.php(249): Contao\Widget::getAttributesFromDca(Array, 'theme_plus_java...', 'a:1:{i:0;s:1:"2...', 'theme_plus_java...', 'tl_page', Object(Contao\DC_Table))
#8 system/modules/core/drivers/DC_Table.php(1888): Contao\DataContainer->row('{title_legend},...')
#9 system/modules/core/classes/Backend.php(434): Contao\DC_Table->edit()
#10 contao/main.php(142): Contao\Backend->getBackendModule('page')
#11 contao/main.php(293): Main->run()
#12 {main}

Warning: Cannot modify header information - headers already sent by (output started at /home/XXX/public_html/XXX/system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 298
#0 [internal function]: __error(2, 'Cannot modify h...', '/home/XXX/...', 298, Array)
#1 system/modules/core/library/Contao/Template.php(298): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(162): Contao\Template->output()
#3 contao/main.php(284): Contao\BackendTemplate->output()
#4 contao/main.php(146): Main->output()
#5 contao/main.php(293): Main->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /home/XXX/public_html/XXX/system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 299
#0 [internal function]: __error(2, 'Cannot modify h...', '/home/XXX/...', 299, Array)
#1 system/modules/core/library/Contao/Template.php(299): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(162): Contao\Template->output()
#3 contao/main.php(284): Contao\BackendTemplate->output()
#4 contao/main.php(146): Main->output()
#5 contao/main.php(293): Main->run()
#6 {main}
```

**Comment by dmolineus** [comment]
Fixed in 6d0375f7d92311d12ebe1b364591cd7083891fdc.
