### ISSUE TITLE
Error beim Installieren der 4.4.2 aus ER

### ISSUE THREAD

**Issue by zonky2** [netzmacht/contao-theme-plus#97]
Beim Installieren der (aktuellen) Version des ER in Contao 3.4.5 kommt folgende Meldung:

```
Fatal error: Query error: Table 'usr_web119_1.tl_theme_plus_javascript' doesn't exist (DESC tl_theme_plus_javascript file) #0 /var/www/web119/html/contao/system/modules/core/library/Contao/Database.php(199): Contao\Database\Statement->query('DESC tl_theme_p...') #1 /var/www/web119/html/contao/system/modules/theme-plus/config/runonce_0.php(24): Contao\Database->query('DESC tl_theme_p...') #2 /var/www/web119/html/contao/system/modules/theme-plus/config/runonce_0.php(14): upgrade_to_contao3_2->updateFileField('tl_theme_plus_j...') #3 /var/www/web119/html/contao/system/modules/theme-plus/config/runonce_0.php(49): upgrade_to_contao3_2->run() #4 /var/www/web119/html/contao/system/modules/theme-plus/config/runonce.php(14): require_once('/var/www/web119...') #5 /var/www/web119/html/contao/system/modules/theme-plus/config/runonce.php(36): runonce_4c1a463ebc3362ceea7bbc35870a9854->run() #6 /var/www/web119/html/contao/system/modules/core/classes/Backend.php(262): include('/var/www/web119...') #7 /var/www/web119/html/contao/system/modules/repository/classes/RepositoryManager.php(483): Contao\Backend->handleRunOnce() #8 /var/www/web119/html/contao/system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database') #9 /var/www/web119/html/contao/system/modules/core/classes/BackendModule.php(91): RepositoryBackendModule->compile() #10 /var/www/web119/html/contao/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate() #11 /var/www/web119/html/contao/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate() #12 /var/www/web119/html/contao/system/modules/core/classes/Backend.php(406): RepositoryManager->generate() #13 /var/www/web119/html/contao/system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('repository_mana...') #14 /var/www/web119/html/contao/contao/main.php(20): Contao\BackendMain->run() #15 {main} in system/modules/theme-plus/config/runonce.php on line 22

#0 [internal function]: __error(256, 'Query error: Ta...', '/var/www/web119...', 22, Array)
#1 system/modules/theme-plus/config/runonce.php(22): trigger_error('Query error: Ta...', 256)
#2 system/modules/theme-plus/config/runonce.php(36): runonce_4c1a463ebc3362ceea7bbc35870a9854->run()
#3 system/modules/core/classes/Backend.php(262): include('/var/www/web119...')
#4 system/modules/repository/classes/RepositoryManager.php(483): Contao\Backend->handleRunOnce()
#5 system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database')
#6 system/modules/core/classes/BackendModule.php(91): RepositoryBackendModule->compile()
#7 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#8 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#9 system/modules/core/classes/Backend.php(406): RepositoryManager->generate()
#10 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('repository_mana...')
#11 contao/main.php(20): Contao\BackendMain->run()
#12 {main}
```

**Comment by dmolineus** [comment]
> Bitte habt Verständnis, dass ich in Zukunft keine Versionen mehr für das ER2 zur Verfügung stellen werde. Wenn sich jemand aus der Community bereit erklärt bei neuen Releases die entsprechende Pakete für das ER2 zu bauen, meldet sich bitte bei mir.

https://community.contao.org/de/showthread.php?55319-Weiterentwicklung-Theme&p=356815&viewfull=1#post356815
