### ISSUE TITLE
$this->User->authenticate(); throws Exception

### ISSUE THREAD

**Issue by daniel-nemeth** [netzmacht/contao-theme-plus#98]
Hi there,
if a front end user is logged in, multiple warnings and errors are thrown.
I already read some articles in Contao forum:
https://community.contao.org/de/showthread.php?43660-logged-in-FE-user-Problem-mit-Session&p=282448&viewfull=1#post282448
https://community.contao.org/de/showthread.php?43660-solved-logged-in-FE-user-Problem-mit-Session

But both solutions doesn't work for me. Is there another solution to fix this problem?
Thanks, Daniel

```
Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in system/modules/core/library/Contao/Database/Mysqli/Statement.php on line 44
#0 [internal function]: __error(2, 'mysqli::real_es...', '/usr/www/users/...', 44, Array)
#1 system/modules/core/library/Contao/Database/Mysqli/Statement.php(44): mysqli->real_escape_string('a:1:{s:7:"refer...')
#2 system/modules/core/library/Contao/Database/Statement.php(347): Contao\Database\Mysqli\Statement->string_escape('a:1:{s:7:"refer...')
#3 system/modules/core/library/Contao/Database/Statement.php(322): Contao\Database\Statement->escapeParams(Array)
#4 system/modules/core/library/Contao/Database/Statement.php(261): Contao\Database\Statement->replaceWildcards(Array)
#5 system/modules/core/classes/FrontendUser.php(95): Contao\Database\Statement->execute('a:1:{s:7:"refer...', '1')
#6 [internal function]: Contao\FrontendUser->__destruct()
#7 {main}

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in system/modules/core/library/Contao/Database/Mysqli/Statement.php on line 44
#0 [internal function]: __error(2, 'mysqli::real_es...', '/usr/www/users/...', 44, Array)
#1 system/modules/core/library/Contao/Database/Mysqli/Statement.php(44): mysqli->real_escape_string('1')
#2 system/modules/core/library/Contao/Database/Statement.php(347): Contao\Database\Mysqli\Statement->string_escape('1')
#3 system/modules/core/library/Contao/Database/Statement.php(322): Contao\Database\Statement->escapeParams(Array)
#4 system/modules/core/library/Contao/Database/Statement.php(261): Contao\Database\Statement->replaceWildcards(Array)
#5 system/modules/core/classes/FrontendUser.php(95): Contao\Database\Statement->execute('a:1:{s:7:"refer...', '1')
#6 [internal function]: Contao\FrontendUser->__destruct()
#7 {main}

Warning: mysqli::query(): Couldn't fetch mysqli in system/modules/core/library/Contao/Database/Mysqli/Statement.php on line 74
#0 [internal function]: __error(2, 'mysqli::query()...', '/usr/www/users/...', 74, Array)
#1 system/modules/core/library/Contao/Database/Mysqli/Statement.php(74): mysqli->query('UPDATE tl_membe...')
#2 system/modules/core/library/Contao/Database/Statement.php(291): Contao\Database\Mysqli\Statement->execute_query()
#3 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#4 system/modules/core/classes/FrontendUser.php(95): Contao\Database\Statement->execute('a:1:{s:7:"refer...', '1')
#5 [internal function]: Contao\FrontendUser->__destruct()
#6 {main}

Warning: Contao\Database\Mysqli\Statement::get_error(): Couldn't fetch mysqli in system/modules/core/library/Contao/Database/Mysqli/Statement.php on line 85
#0 system/modules/core/library/Contao/Database/Mysqli/Statement.php(85): __error(2, 'Contao\\Database...', '/usr/www/users/...', 85, Array)
#1 system/modules/core/library/Contao/Database/Statement.php(118): Contao\Database\Mysqli\Statement->get_error()
#2 system/modules/core/library/Contao/Database/Statement.php(293): Contao\Database\Statement->__get('error')
#3 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#4 system/modules/core/classes/FrontendUser.php(95): Contao\Database\Statement->execute('a:1:{s:7:"refer...', '1')
#5 [internal function]: Contao\FrontendUser->__destruct()
#6 {main}

Fatal error: Uncaught exception 'Exception' with message 'Query error: (UPDATE tl_member SET session='' WHERE id='')' in /usr/www/users/qpvmbm/portal/system/modules/core/library/Contao/Database/Statement.php:293 Stack trace: #0 /usr/www/users/qpvmbm/portal/system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query() #1 /usr/www/users/qpvmbm/portal/system/modules/core/classes/FrontendUser.php(95): Contao\Database\Statement->execute('a:1:{s:7:"refer...', '1') #2 [internal function]: Contao\FrontendUser->__destruct() #3 {main} thrown in /usr/www/users/qpvmbm/portal/system/modules/core/library/Contao/Database/Statement.php on line 293
```

**Comment by dmolineus** [comment]
Which version do you use? This is probably an incompatibility between different extensions but can be solved by Theme+. Could you please give me the list of installed modules?

**Comment by contaolove** [comment]
We are using Contao 3.4.4 with ThemePlus 4.4.3. And here is our full list of extensions we are using.

![screen shot 2015-07-22 at 16 00 58](https://cloud.githubusercontent.com/assets/13376752/8827121/f872c44c-308a-11e5-9d74-3485788f77f1.png)

**Comment by dmolineus** [comment]
I hope this commit b9ee9a7e45584bbfc2bfb2b26300a9f8db2688ef fixes it. I didn't get the issue, so please install the current dev branch (dev-support/4.x) and confirm if the issue got fixed.

**Comment by dmolineus** [comment]
What happens if you deactive the Theme+ extension? Does the error still occurs? This error can be caused by any extension.

**Comment by daniel-nemeth** [comment]
Ok, I will check all extensions.

I'm very sorry if you aren't responsible for this defect, because of the forum entries is supposed your extension could be the problem.

I hope i can finish the test this week.
Thanks

**Comment by dmolineus** [comment]
Closed because of lack of response. If it still occurs feel free to report again.
